name: gitvision
description: "Eurovision-themed GitHub commit mood analyzer with Spotify integration for 120-minute developer workshop"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.0
  audioplayers: ^6.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.0
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/eurovision_github_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon/eurovision_github_icon_foreground.png"
  ios_content_mode: scaleAspectFit
  macos:
    generate: true
    image_path: "assets/icon/eurovision_github_icon.png"
