import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'dart:convert';

class ModernShareWidget extends StatelessWidget {
  final Map<String, dynamic> playlistData;
  final String? githubHandle;

  const ModernShareWidget({
    super.key,
    required this.playlistData,
    this.githubHandle,
  });

  @override
  Widget build(BuildContext context) {
    return ElevatedButton.icon(
      icon: const Icon(Icons.share),
      label: const Text('Share Playlist'),
      onPressed: () => _sharePlaylist(),
    );
  }

  void _sharePlaylist() {
    final mood = playlistData['playlist']['mood'] as String;
    final songs = playlistData['playlist']['songs'] as List;
    
    final songList = songs.map((song) => 
      '${song['title']} - ${song['artist']} (${song['country']} ${song['year']})'
    ).join('\n');
    
    final text = '''
🎵 GitVision Eurovision Playlist 🎵
${githubHandle != null ? 'For @$githubHandle' : ''}
Mood: $mood

$songList

Generated by GitVision - GitHub commit analyzer with Eurovision vibes! 🎤
''';

    Share.share(text);
  }
}
